name: Deploy DFC-Studios

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    - name: Execute deployment script
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        set -e
        ssh -o StrictHostKeyChecking=no ${{ env.USERNAME }}@${{ env.HOST }} "cd /home/lando/scripts && ./deploy-studios.sh"
        EXIT_STATUS=$?
        echo "Deployment script exited with status $EXIT_STATUS"
        exit $EXIT_STATUS
  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: Notify via Resend
        uses: brunosj/actions/resend-notify@v1
        with:
          subject: "GitHub Actions - Deploy DFC Studios Failed"
          resend_api_key: ${{ secrets.RESEND_API_KEY }}

